### ISSUE TITLE
Cannot find a library instance of "LibProfessions-1.0".

### ISSUE THREAD

**Issue by fireymerlin** [Beast-Masters-addons/LibProfessions#2]
I cannot get this to load.

I'm getting
Cannot find a library instance of "LibProfessions-1.0".

I copied ProfessionApi.lua, LibProfessions.lua, CurrentProfession.lua to the top my addons folder.
I added the following lines to my vanilla.toc file before the line that runs my addon
ProfessionApi.lua
LibProfessions.lua
CurrentProfession.lua
I added this line to my addon.
local professions = LibStub("LibProfessions-1.0")

I've looked at _g.LibStub.libs and I don't see LibProfessions.
What am I doing incorrect?

**Comment by datagutten** [comment]
The readme was outdated and not correct, I have updated it with more detailed information now.
